In [46]:
#data Preparation

import pandas as pd
from preprocess import preprocess_text

#loading the data
train_set = pd.read_csv('semEval dataest/semeval-2017-train.csv', delimiter='\t')
test_set = pd.read_csv('semEval dataest/semeval-2017-test.csv', delimiter='\t')
dev_set = pd.read_csv('semEval dataest/semeval-2017-dev.csv', delimiter='\t')

#preprocessing the data
train_set['text'] = train_set['text'].apply(preprocess_text)
train_set.head()

label                                               text
0      1  walking chelsea time day rather lovely love lo...
1      0  first play night aaron rodgers int udfa cb bra...
2      0  drove bike today miles felt like jim carrey irene
3     -1  looking temp outside hpw get hotter sun goes f...
4      0  rt redarmy therefore still expect arsenal sign...

In [48]:
import tensorflow as tf
from transformers import TFBertModel, BertTokenizer

# Loading  BERT model architecture
bert_model = TFBertModel.from_pretrained('bert-base-uncased')

# Loading BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Example
input_text = "Hello, how are you?"
input_ids = tokenizer.encode(input_text, add_special_tokens=True)
inputs = tf.constant([input_ids])

# Get BERT model outputs
outputs = bert_model(inputs)
outputs


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 8, 768), dtype=float32, numpy=
array([[[-0.08241846,  0.066673  , -0.28802308, ..., -0.356556  ,
          0.19599804,  0.5381451 ],
        [ 0.0310358 , -0.14484859,  0.09522495, ..., -0.15599121,
          1.0150981 ,  0.0946566 ],
        [-0.8935157 ,  0.3240218 ,  0.4184377 , ..., -0.5498075 ,
          0.28525218,  0.11490025],
        ...,
        [-0.28124642, -0.85312325,  0.6912379 , ..., -0.50514704,
          0.4716185 , -0.6854342 ],
        [-0.44294897, -0.78202313, -0.80554706, ...,  0.19494341,
          0.1081038 ,  0.01300353],
        [ 0.55699295, -0.10795444, -0.24119982, ...,  0.28168672,
         -0.39957324, -0.18823323]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.939707  , -0.40806657, -0.9024413 ,  0.8667438 ,  0.6075713 ,
        -0.17818435,  0.93191355,  0.26847416, -0.7918063 , -0.9999916 ,
        -0.4899121 ,  0.9624